### ISSUE TITLE
Getting Error After Replacing My Exported Key In Config File 

### ISSUE THREAD

**Issue by merahul947** [xkrisl/VMProtect-Tools#1]
Enter customers HWID...

Error: System.Xml.XmlException: There is an unclosed literal string. Line 1, position 58.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at VMProtect.KeyGen.Generator..ctor(String data)
   at LicenseGen.Program.Main(String[] args) in E:\1 Vm Keygen Proj\VMProtect-Tools-C#\VMProtect-Tools-df906dd166da82db0baae6481cafdd311e5f6fa3\LicenseGen\Program.cs:line 34

**Comment by xkrisl** [comment]
The issue is in your Config.ini. 
Make sure the RSA key is all on a single line, not multiple lines. So remove the spacing between them.
It should look like this:
https://prnt.sc/zw9jtc

It will fix your issue.
